### ISSUE TITLE
about send multipart/formdata

### ISSUE THREAD

**Issue by QingWei-Li** [fdaciuk/ajax#19]
Hi,

When we set `'content-type':  'multipart/formdata'` and send formdata. The server will return error, due to no **boundary** in the 'content-type'. 

I think we can when setting the 'content-type' to **false**, do not set content-type in header. like
```javascript
      if ($private.hasContentType(headers) === undefined) {
        headers['Content-Type'] = 'application/x-www-form-urlencoded'
      }
```
what do you think?

reference: http://stackoverflow.com/questions/5392344/sending-multipart-formdata-with-jquery-ajax

**Comment by fdaciuk** [comment]
Hey @QingWei-Li, good catch! =)
I didn't know about it. I'll put an option to remove the `content-type`. Thanks!

**Comment by kazzkiq** [comment]
Just stumbled in the same issue on my project. Can't upload images. :(

Any progress with this issue?

**Comment by fdaciuk** [comment]
I'm working on it =)

**Comment by fdaciuk** [comment]
Done =)
Now, just use:

```js
ajax({
  headers: { 'content-type': null }
})
```

:dancer: :dancer: :sparkles:
