### ISSUE TITLE
Add option for base URL 

### ISSUE THREAD

**Issue by kazzkiq** [fdaciuk/ajax#23]
First things first: **BADASS plugin!** Saving me big time! 😄 

A common thing when consuming REST APIs via CORS is always using the same base URL for all AJAX calls. E.g.

```js
ajax().get('https://my-url.here/service/etc')
ajax().get('https://my-url.here/service/abc')
ajax().get('https://my-url.here/service/something')
ajax().get('https://my-url.here/service/another-something')
```

This gets overwhelming to type for each single new AJAX call. Maybe it would be interesting to enable user to set a base URL from where requests would start from? E.g.

```js
ajax().registerBaseUrl('https://my-url.here/service')

ajax().get('/etc')
ajax().get('/abc')
ajax().get('/something')
ajax().get('/another-something')
```

then if user really needs to use another URL they could just start the request with `http|https` (or another major protocol). E.g.

```js
ajax().registerBaseUrl('https://my-url.here/service')

ajax().get('/etc')                                 // https://my-url.here/service/etc
ajax().get('https://another-service.here/data')    // https://another-service.here/data
```

Do you think its a good idea?

**Comment by fdaciuk** [comment]
Hey @kazzkiq! I'm glad you're enjoying it =)
But, I don't know.. Can you show me a real example for this problem?

The point is: every call to `ajax()` function creates a new `XMLHttpRequest` instance.
If you want to force a base url, it will be necessary to add a static method on `ajax` object, like this:

```js
ajax.baseUrl('http://example.com')
```

And then, every call to `ajax()` would be using this base url. But that seems not the right way to do it xD

I'm thinking about it. Give me a bit of time xD

**Comment by kazzkiq** [comment]
@fdaciuk Yeah thats exactly what I thought. As `ajax()` is a singleton, by setting a `baseUrl` you would be changing all the other AJAX calls too.

Thats the biggest downside of this approach. If a developer overrides it from another place, all other devs/AJAX calls are affected too (although I think this can easily be solved with a proper app architecture).

However, as I said, most client-side applications would always consume from the same API, so despite the issue above, it also makes sense to set a `baseUrl` as default and only change that on specific cases.

**Real example:**

Imagine you're building a Twitter client. You're going to enable search, feed, hashtag filters and such. All those actions are under an API that use the same base URL: `https://api.twitter.com/1.1/`. The same goes for Facebook, and for other big services, and for mainstream projects too. You generally always consume from the same place. And what if the API changes? Would you need to replace all your `ajax()` URLs? Why not just replace the `baseUrl()` value and watch it work flawlessly?

If this is not true for some application, the user can simply not register any `baseUrl`. However, in most common cases I think it would be useful to configure this `baseUrl` on startup and then just use `ajax()` omitting the base of the URL.

----

Of course one could simply create an abstract class which sets an URL and then pass it like:

```js
ajax().get(API.baseUrl + '/etc/abc')
```

However I think a solution **built in** the library would aggregate to its value and usability.

**Comment by fdaciuk** [comment]
Hey @kazzkiq! Sorry for the delay xD

In actual version, this is impossible without cause bugs, because I am using return object with `then`, `catch` and `always` methods as a reference.

But the good news is: I am working in a `v2` for this library, in a more functional approach, and I have ever implemented this feature xD

Look here: https://github.com/fdaciuk/ajax/tree/version-2.0.0-beta.0

All tests are passing! If you could test, I really thank you =)

**Comment by kazzkiq** [comment]
Hey @fdaciuk , I did a rapid test here and it worked like a charm! Very good! :)

**Comment by fdaciuk** [comment]
Thanks @kazzkiq :dancer: :dancer: :sparkles:

**Comment by fdaciuk** [comment]
It was added on v2.0 =)
Thanks for your contribution :D
