### ISSUE TITLE
Browser Compatibility 

### ISSUE THREAD

**Issue by spartman** [fdaciuk/ajax#28]
Hi fdaciuk,

Could you confirm what are the browser version that fully supports your package?

Cheers
E

**Comment by fdaciuk** [comment]
Hi @spartman!

According to http://jscc.info/, that is the compatibility table:

Browser | Version
--- | ---
Chrome |  4 to 41
Firefox | 2 to 36
IE | 9 to 11
iOS Safari | 3.2 to 8
Opera  | 9.5-9.6 to 27
Opera Mini | 5.0-8.0
Safari | 3.1 to 8
