### ISSUE TITLE
Create Bower package

### ISSUE THREAD

**Issue by kazzkiq** [fdaciuk/ajax#3]
It would be interesting to have this library available over Bower.

More info about creating a package can be found here: http://bower.io/docs/creating-packages/

**Comment by fdaciuk** [comment]
This library is already on Bower: http://bower.io/search/?q=ajax
Look the first result :smile:

**Comment by gbrlsepulveda** [comment]
@fdaciuk Have any plans to publish in npm?

**Comment by fdaciuk** [comment]
@gbrlsepulveda I don't think so. NPM has a package called `ajax` already. But I could put with another name.

But I need to think better about it.

**Comment by luanmuniz** [comment]
You can use namespace "@fdaciuk/ajax"

**Comment by fdaciuk** [comment]
> You can use namespace "@fdaciuk/ajax"

@luanmuniz namespaces are not just for private modules?

**Comment by luanmuniz** [comment]
@fdaciuk No, you can use it in public projects too
http://blog.npmjs.org/post/116936804365/solving-npms-hard-problem-naming-packages

**Comment by fdaciuk** [comment]
Very nice @luanmuniz! I will do this :)
Thanks :dancer: :dancer:

**Comment by gbrlsepulveda** [comment]
Nice, good solution @luanmuniz 

Thanks @fdaciuk

**Comment by fdaciuk** [comment]
@gbrlsepulveda done! :dancers: :sparkles: :dancer: @luanmuniz: thanks again!

https://github.com/fdaciuk/ajax#commonjs-via-npm
