### ISSUE TITLE
"Promise" api is not a proper thenable

### ISSUE THREAD

**Issue by statianzo** [fdaciuk/ajax#37]
Converting ajax "promises" into real Promises with `Promise.resolve` doesn't work. Successful case is fine. However, if there's an error (or abort), `catch` in the wrapping Promise doesn't get called.

Changing the `.then(onFulfilled)` method to be `.then(onFulfilled, onRejected)`, would make this a proper thenable and allow any promise library to wrap it.

```js
const req = ajax({/* ... */});
const realPromise = Promise.resolve(req);
realPromise
  .then(() => console.log('worked')
  .catch(() => console.log('failed'))
// 'failed' will never show if an error happens
```

https://jsfiddle.net/w90fk864/1/

**Comment by fdaciuk** [comment]
Yeap, it's not a real Promise implementation. We have another opened issue about this on #20 =)
PRs are welcome =)
