### ISSUE TITLE
Missing character causes error

### ISSUE THREAD

**Issue by jenstornell** [fdaciuk/ajax#42]
**The js ends with:**

```js
 return ajax
})
```

That cases and error if I merge it with other javascripts.

**Change it to:**

```js
 return ajax
});
```

**Comment by fdaciuk** [comment]
Hi @jenstornell! Could you show me the code are you using?

**Comment by jenstornell** [comment]
https://github.com/fdaciuk/ajax/blob/dev/src/ajax.js#L125

**Comment by fdaciuk** [comment]
Yes, this is the lib code, and it is ok. I want to see your code =)

But to fix it, you should add a semicolon on your code, if you are using IIFE, for example, [like this](https://github.com/fdaciuk/ajax/blob/dev/src/ajax.js#L1).

**Comment by fdaciuk** [comment]
@jenstornell you should use [minified code](https://github.com/fdaciuk/ajax/blob/dev/dist/ajax.min.js) too, instead of source.

**Comment by jenstornell** [comment]
I combine ajax.js with this file: https://github.com/Alex-D/Cookies-EU-banner/blob/master/src/cookies-eu-banner.js (cookie script last).

**Comment by jenstornell** [comment]
About minified code... I don't like to use the minified code. Instead I use Gulp to minify it. That way it's easier for me to debug it on the localhost. So, minified on the live server, not minified on the localhost.

**Comment by fdaciuk** [comment]
No problem about minified code. You can use source in this case =)

> Maybe it's a semicolon missing in the cookie js then?

Yes, adding a semicolon at the first position, it should works like a charm =)
