### ISSUE TITLE
Add PATCH support

### ISSUE THREAD

**Issue by pwFoo** [fdaciuk/ajax#43]
Because it's used by RESTful APIs I think.
http://www.restapitutorial.com/lessons/httpmethods.html

**Comment by fdaciuk** [comment]
Hey @pwFoo! You can use any http method, following [this way](https://github.com/fdaciuk/ajax#options).

Please, let me know if you have any other doubt =)

**Comment by pwFoo** [comment]
Haven't tested it, but found this line which looked like a limit.

>   function ajax (options) {
>       var methods = ['get', 'post', 'put', 'delete']

Thank's. I'll test it out.

**Comment by fdaciuk** [comment]
It is just to create the methods `.get()`, `.post()`, `.put()` and `.delete()`, directly on the `ajax` returned object.

But you can use any http method, following the example on documentation =)

**Comment by pwFoo** [comment]
I got it during go through your source code. Thanks!
Maybe I convert your code to a plugin for my use case with a small library to remove my jquery dependency :)

Thanks for sharing your great work here 👍

**Comment by fdaciuk** [comment]
Nice =)
