### ISSUE TITLE
Use fetch with XMLHttpRequest fallback?

### ISSUE THREAD

**Issue by pwFoo** [fdaciuk/ajax#45]
Because I found some information about fetch and improved browser support. Should XMLHttpRequest replaced by fetch with a fallback for unsupported browsers like IE or some mobile browsers?

**Comment by fdaciuk** [comment]
Yes, you can do it. There are some libraries that do this. A polyfill that you may use is [github/fetch](https://github.com/github/fetch). =)

**Comment by pwFoo** [comment]
Fetch browser support is good today, but misses IE, IE mobile and support just the latest Safari and Android browser... Compared in file size between fetch polyfill and your ajax solution I think I stay with ajax at the moment. :)

**Comment by fdaciuk** [comment]
That is the point ;)
