### ISSUE TITLE
add 'get' data support

### ISSUE THREAD

**Issue by liq-personal-2017** [fdaciuk/ajax#50]
xhr.send(data) will ignore data while the method is GET,so i decide to serialize data and put it in the end of url
just like this:

//other my code
        if (opt.type === 'GET' && opt.data2send !== null) {
                if (url.indexOf('?') === -1) {
                    url += '?';
                } else {
                    url += '&';
                }
                url += serilizeData(opt.data2send);
       }
//other my code
function serializeData(data) {
        if ('object' === typeof data) {
            return _.map(data, function (key, value) {
                return [key, '=', ('object' === typeof value ? JSON.stringify(value) : String(value))].join('');
            }).join('&');
        } else {
            return String(data);
        }
    }
so , if you can add get 'data' support in this project?
thank you very much.

**Comment by fdaciuk** [comment]
Hi @liq-personal-2017! Thanks for suggestion! I think it really makes sense! Let's implement it =)
