### ISSUE TITLE
Send [object object] from method PUT 

### ISSUE THREAD

**Issue by nicholasess** [fdaciuk/ajax#54]
Hi @fdaciuk, i`m try to send a object to endpoint, but the network in browser show [object object].

my code:
```
  let url = 'http://localhost:3000/api'
  let request = (param, data) = ajax({
    method: "put",
    url: url + param,
    data: data,
  }); 

  request(`/users/1`, { driverDocument: { status: 2 } }).then()
```

Network

![captura de tela 2018-06-19 as 09 15 46](https://user-images.githubusercontent.com/3238901/41596752-b0d73fe8-73a1-11e8-99ad-ab5dca0be239.png)

**Comment by fdaciuk** [comment]
Hey @nicholasess! It's definitely a bug :\
The library is ready to accept an object with just one level.

I'll fix it =)

**Comment by nicholasess** [comment]
Nice man, i always use the library, but i changed to axios in project to finish my job. When you fixed it, tell me about.

Thanks

**Comment by fdaciuk** [comment]
@nicholasess can you try it again with new version?

**Comment by fdaciuk** [comment]
I'll close this issue because the problem was already solved. But if you want any other trouble, just let me know =)
