### ISSUE TITLE
Shouldn't 2.3.1 be a new minor version?

### ISSUE THREAD

**Issue by erikchs** [fdaciuk/ajax#57]
Hi There,

Nice project! Have been using it in a couple of projects, works good. The docs state the following;

```
Passing data as object, application/json will be automatically used (since v2.3.1).
```

Shouldn't that be a minor (or even major) SemVer? E.g. `2.4.0`? Had my dependencies set to `^2.3.0` and after a update my whole project stopped working.

Minor issue, easy fix, but took some time to figure out what had changed (until i read your docs again).

Thanks!

**Comment by fdaciuk** [comment]
Hi @erikchs! Sorry for that :\
I'll get back the version `2.3.0` in the next `2.3.3`.

Could you show me how is your code - that have broken because of that update?

Thanks for reporting that!

**Comment by erikchs** [comment]
Yeah the sole issue was that `application/json` was all of a sudden used instead of `application/x-www-form-urlencoded` when sending data as a `object`. I was sending data as an `object` everywhere, and my back-end was expecting to receive 'old-school' `$_POST` variables.

Issue is fixed now, just figured it should be a minor (or major) upgrade, since the API had non backwards compatible changes ;)

**Comment by fdaciuk** [comment]
Nice! Thanks for sharing! I'm going to create a major version then, just in case =)
And I've already reverted the version `v2.3.0` to `v2.3.3`. =)

Thanks again for reporting! And let me know if you have any other issue =)
