### ISSUE TITLE
Error when using method options

### ISSUE THREAD

**Issue by aalfiann** [fdaciuk/ajax#61]
I've tried like this

```js
var request = ajax({
  method: 'options',
  url: '/api/users',
  data: JSON.stringify({
    user: 'john'
  })
});

request.then(function (response) {...});
```

but I got error **request.then is not a function**?
what's wrong?

**Comment by fdaciuk** [comment]
Hi @aalfiann! I've tried the exact same code, and everything works just fine =)
Did you install the library on your project?

**Comment by aalfiann** [comment]
Sorry late for reply..

I use this library by using cdn, so should I install this to make this work?

**Comment by fdaciuk** [comment]
When using from CDN, you don't have to install anything else.
I tried here, and it works well either.

Check if you have `ajax` function is available globally (check the result of `console.log(ajax)`).
If it is not, try to use `window.ajax()` or `globalThis.ajax()` instead of just `ajax()` ;)

**Comment by aalfiann** [comment]
awesome, I use `window.ajax()` and its working now.. thanks
